<?php

namespace App\Repositories;

use Illuminate\Support\ServiceProvider;

class RepositoriesServiceProvider extends ServiceProvider
{
    public function register()
    {
        $this->app->bind(
            'App\Repositories\Interface\StaffInterface',
            'App\Repositories\StaffRepositories',
        );
        $this->app->bind(
            'App\Repositories\Interface\BranchInterface',
            'App\Repositories\BranchRepositories',
        );
        $this->app->bind(
            'App\Repositories\Interface\DivisionInterface',
            'App\Repositories\DivisionRepositories',
        );
        $this->app->bind(
            'App\Repositories\Interface\DistrictInterface',
            'App\Repositories\DistrictRepositories',
        );
        $this->app->bind(
            'App\Repositories\Interface\UpazillaInterface',
            'App\Repositories\UpazillaRepositories',
        );
        $this->app->bind(
            'App\Repositories\Interface\BatchInterface',
            'App\Repositories\BatchRepositories',
        );
        $this->app->bind(
            'App\Repositories\Interface\GalleryInterface',
            'App\Repositories\GalleryRepositories',
        );
        $this->app->bind(
            'App\Repositories\Interface\StudentInterface',
            'App\Repositories\StudentRepositories',
        );
        $this->app->bind(
            'App\Repositories\Interface\CourseInterface',
            'App\Repositories\CourseRepositories',
        );
        $this->app->bind(
            'App\Repositories\Interface\CourseDetailsInterface',
            'App\Repositories\CourseDetailsRepositories',
        );
        $this->app->bind(
            'App\Repositories\Interface\BoardInterface',
            'App\Repositories\BoardRepositories',
        );
        $this->app->bind(
            'App\Repositories\Interface\SessionInterface',
            'App\Repositories\SessionRepositories',
        );
        $this->app->bind(
            'App\Repositories\Interface\ExaminationInterface',
            'App\Repositories\ExaminationRepositories',
        );
        $this->app->bind(
            'App\Repositories\Interface\AdmissionPaymentInterface',
            'App\Repositories\AdmissionPaymentRepositories',
        );
        $this->app->bind(
            'App\Repositories\Interface\ServiceInterface',
            'App\Repositories\ServiceRepositories',
        );
        $this->app->bind(
            'App\Repositories\Interface\CounterInterface',
            'App\Repositories\CounterRepositories',
        );
        $this->app->bind(
            'App\Repositories\Interface\AchiveStudentInterface',
            'App\Repositories\AchiveStudentRepositories',
        );
        $this->app->bind(
            'App\Repositories\Interface\EventInterface',
            'App\Repositories\EventRepositories',
        );
        $this->app->bind(
            'App\Repositories\Interface\BannerSectionInterface',
            'App\Repositories\BannerSectionRepositories',
        );
        $this->app->bind(
            'App\Repositories\Interface\SettingInterface',
            'App\Repositories\SettingRepositories',
        );
        $this->app->bind(
            'App\Repositories\Interface\ResultInterface',
            'App\Repositories\ResultRepositories',
        );
        $this->app->bind(
            'App\Repositories\Interface\RegisterInterface',
            'App\Repositories\RegisterRepositories',
        );
    }
}
